# Generated by Django 5.0.1 on 2024-01-14 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование банка')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
            },
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_period', models.DateField(verbose_name='Начало отчета')),
                ('end_period', models.DateField(verbose_name='Конец отчета')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheet', to='osv.bank', verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Балансовая ведомость',
                'verbose_name_plural': 'Балансовые ведомости',
            },
        ),
        migrations.CreateModel(
            name='FinancialClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(verbose_name='Номер класса')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование класса')),
                ('balance_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_classes', to='osv.balancesheet', verbose_name='Балансовая ведомость')),
            ],
            options={
                'verbose_name': 'Финансовый класс',
                'verbose_name_plural': 'Финансовые классы',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, verbose_name='Код счета')),
                ('financial_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='osv.financialclass', verbose_name='Финансовый класс')),
            ],
            options={
                'verbose_name': 'Банковский счет',
                'verbose_name_plural': 'Банковские счета',
            },
        ),
        migrations.CreateModel(
            name='FinancialGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('start_balance', 'Входящее сальдо'), ('turnover', 'Обороты'), ('end_balance', 'Исходящее сальдо')], max_length=30, verbose_name='Тип группы')),
                ('balance_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_groups', to='osv.balancesheet', verbose_name='Балансовая ведомость')),
            ],
            options={
                'verbose_name': 'Финансовая группа',
                'verbose_name_plural': 'Финансовые группы',
            },
        ),
        migrations.CreateModel(
            name='FinancialSubtype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('active', 'Актив'), ('passive', 'Пассив'), ('debit', 'Дебит'), ('credit', 'Кредит')], max_length=30, verbose_name='Тип группы')),
                ('financial_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_subtypes', to='osv.financialgroup', verbose_name='Финансовая группа')),
            ],
            options={
                'verbose_name': 'Финансовая подгруппа',
                'verbose_name_plural': 'Финансовые подгруппы',
            },
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Значение')),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='osv.bankaccount', verbose_name='Банковский счет')),
                ('financial_subtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='osv.financialsubtype', verbose_name='Финансовая подгруппа')),
            ],
            options={
                'verbose_name': 'Финансовая отчетность',
                'verbose_name_plural': 'Финансовые отчетности',
            },
        ),
    ]
