# Generated by Django 5.0.1 on 2024-01-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'ordering': ('code',), 'verbose_name': 'Банковский счет', 'verbose_name_plural': 'Банковские счета'},
        ),
        migrations.AlterModelOptions(
            name='financialclass',
            options={'ordering': ('number',), 'verbose_name': 'Финансовый класс', 'verbose_name_plural': 'Финансовые классы'},
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='file',
            field=models.FileField(default=1, upload_to='balance_sheets/', verbose_name='Файл балансовой ведомости'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Наименование банка'),
        ),
        migrations.AlterField(
            model_name='financialgroup',
            name='name',
            field=models.CharField(choices=[('Входящее сальдо', 'Входящее сальдо'), ('Обороты', 'Обороты'), ('Исходящее сальдо', 'Исходящее сальдо')], max_length=30, verbose_name='Тип группы'),
        ),
        migrations.AlterField(
            model_name='financialsubtype',
            name='name',
            field=models.CharField(choices=[('Актив', 'Актив'), ('Пассив', 'Пассив'), ('Дебит', 'Дебит'), ('Кредит', 'Кредит')], max_length=30, verbose_name='Тип группы'),
        ),
        migrations.AddConstraint(
            model_name='balancesheet',
            constraint=models.UniqueConstraint(fields=('start_period', 'end_period', 'bank'), name='uniq_balance_sheet'),
        ),
        migrations.AddConstraint(
            model_name='bankaccount',
            constraint=models.UniqueConstraint(fields=('code', 'financial_class'), name='uniq_bank_account'),
        ),
        migrations.AddConstraint(
            model_name='financialclass',
            constraint=models.UniqueConstraint(fields=('number', 'name', 'balance_sheet'), name='uniq_financial_class'),
        ),
    ]
