# Generated by Django 5.0.1 on 2024-01-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.CharField(max_length=1)),
            ],
        ),
        migrations.AlterModelOptions(
            name='jointbankaccount',
            options={'ordering': ('financial_class', 'code'), 'verbose_name': 'Объединенный банковский счет', 'verbose_name_plural': 'Объединенные банковские счета'},
        ),
    ]
