# Generated by Django 5.0.1 on 2024-01-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='value_1',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='value_2',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='value_3',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='value_4',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='value_5',
        ),
        migrations.RemoveField(
            model_name='bankaccount',
            name='value_6',
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='end_balance_active_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Значение: Исходящее сальдо | Актив '),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='end_balance_passive_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Значение: Исходящее сальдо | Актив '),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='start_balance_active_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40, verbose_name='Значение: Входящее сальдо | Актив '),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='start_balance_passive_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40, verbose_name='Значение: Входящее сальдо | Актив '),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='turnover_credit_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40, verbose_name='Значение: Обороты | Кредит '),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='turnover_debit_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40, verbose_name='Значение: Обороты | Дебит '),
        ),
    ]
