# Generated by Django 5.0.1 on 2024-01-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osv', '0002_remove_bankaccount_value_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='end_balance_passive_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Значение: Исходящее сальдо | Пассив '),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='start_balance_passive_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40, verbose_name='Значение: Входящее сальдо | Пассив '),
        ),
    ]
