# Generated by Django 5.0.1 on 2024-01-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osv', '0002_alter_bankaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatement',
            name='value',
            field=models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Значение'),
        ),
    ]
