# Generated by Django 5.0.1 on 2024-01-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osv', '0002_test_alter_jointbankaccount_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancesheet',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='balance_sheets/', verbose_name='Файл балансовой ведомости'),
        ),
    ]
