# Generated by Django 5.0.1 on 2024-01-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('osv', '0003_alter_balancesheet_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AlterModelOptions(
            name='financialclass',
            options={'ordering': ('balance_sheet', 'number'), 'verbose_name': 'Финансовый класс', 'verbose_name_plural': 'Финансовые классы'},
        ),
    ]
