# Generated by Django 5.0.1 on 2024-01-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osv', '0003_alter_bankaccount_end_balance_passive_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialclass',
            name='end_balance_passive_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Значение: Исходящее сальдо | Пассив '),
        ),
        migrations.AddField(
            model_name='financialclass',
            name='total_class_end_balance_active_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Итоговое значение по классу: Исходящее сальдо | Актив '),
        ),
        migrations.AddField(
            model_name='financialclass',
            name='total_class_start_balance_active_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Итоговое значение по классу: Входящее сальдо | Актив '),
        ),
        migrations.AddField(
            model_name='financialclass',
            name='total_class_start_balance_passive_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Итоговое значение по классу: Входящее сальдо | Пассив '),
        ),
        migrations.AddField(
            model_name='financialclass',
            name='total_class_turnover_credit_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Итоговое значение по классу: Обороты | Кредит '),
        ),
        migrations.AddField(
            model_name='financialclass',
            name='total_class_turnover_debit_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Итоговое значение по классу: Обороты | Дебит '),
        ),
    ]
