# Generated by Django 5.0.1 on 2024-01-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osv', '0003_alter_financialstatement_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatement',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=40, verbose_name='Значение'),
        ),
    ]
