# Generated by Django 5.0.1 on 2024-01-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osv', '0005_remove_financialclass_end_balance_passive_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancesheet',
            name='total_balance_end_balance_active_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Итоговое значение по балансу: Исходящее сальдо | Актив '),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='total_balance_end_balance_passive_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Итоговое значение по балансу: : Исходящее сальдо | Пассив '),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='total_balance_start_balance_active_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Итоговое значение по балансу: Входящее сальдо | Актив '),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='total_balance_start_balance_passive_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Итоговое значение по балансу: Входящее сальдо | Пассив '),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='total_balance_turnover_credit_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Итоговое значение по балансу: Обороты | Кредит '),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='total_balance_turnover_debit_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Итоговое значение по балансу: Обороты | Дебит '),
        ),
    ]
