# Generated by Django 5.0.1 on 2024-01-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osv', '0006_balancesheet_total_balance_end_balance_active_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancesheet',
            name='total_balance_end_balance_active_value',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='total_balance_end_balance_passive_value',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='total_balance_start_balance_active_value',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='total_balance_start_balance_passive_value',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='total_balance_turnover_credit_value',
        ),
        migrations.RemoveField(
            model_name='balancesheet',
            name='total_balance_turnover_debit_value',
        ),
        migrations.RemoveField(
            model_name='financialclass',
            name='total_class_end_balance_active_value',
        ),
        migrations.RemoveField(
            model_name='financialclass',
            name='total_class_end_balance_passive_value',
        ),
        migrations.RemoveField(
            model_name='financialclass',
            name='total_class_start_balance_active_value',
        ),
        migrations.RemoveField(
            model_name='financialclass',
            name='total_class_start_balance_passive_value',
        ),
        migrations.RemoveField(
            model_name='financialclass',
            name='total_class_turnover_credit_value',
        ),
        migrations.RemoveField(
            model_name='financialclass',
            name='total_class_turnover_debit_value',
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='end_balance_active_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Значение: Исходящее сальдо | Актив '),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='end_balance_passive_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Итоговое значение: : Исходящее сальдо | Пассив '),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='start_balance_active_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40, verbose_name='Значение: Входящее сальдо | Актив '),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='start_balance_passive_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40, verbose_name='Значение: Входящее сальдо | Пассив '),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='turnover_credit_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40, verbose_name='Значение: Обороты | Кредит '),
        ),
        migrations.AddField(
            model_name='balancesheet',
            name='turnover_debit_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40, verbose_name='Значение: Обороты | Дебит '),
        ),
        migrations.AddField(
            model_name='financialclass',
            name='end_balance_active_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Значение: Исходящее сальдо | Актив '),
        ),
        migrations.AddField(
            model_name='financialclass',
            name='end_balance_passive_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Итоговое значение: : Исходящее сальдо | Пассив '),
        ),
        migrations.AddField(
            model_name='financialclass',
            name='start_balance_active_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40, verbose_name='Значение: Входящее сальдо | Актив '),
        ),
        migrations.AddField(
            model_name='financialclass',
            name='start_balance_passive_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40, verbose_name='Значение: Входящее сальдо | Пассив '),
        ),
        migrations.AddField(
            model_name='financialclass',
            name='turnover_credit_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40, verbose_name='Значение: Обороты | Кредит '),
        ),
        migrations.AddField(
            model_name='financialclass',
            name='turnover_debit_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40, verbose_name='Значение: Обороты | Дебит '),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='end_balance_passive_value',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Расчитывается автоматически после сохранения', max_digits=40, verbose_name='Итоговое значение: : Исходящее сальдо | Пассив '),
        ),
    ]
